/* auto-generated by permit0-node build */

/** Permission decision values. */
export const enum Permission {
  Allow = "Allow",
  Human = "Human",
  Deny = "Deny",
}

/** Risk tier values. */
export const enum Tier {
  Minimal = "Minimal",
  Low = "Low",
  Medium = "Medium",
  High = "High",
  Critical = "Critical",
}

/** Risk score output from the scoring pipeline. */
export interface RiskScore {
  /** Raw score 0.0–1.0. */
  raw: number;
  /** Display score 0–100. */
  score: number;
  /** Risk tier. */
  tier: Tier;
  /** Flags that fired. */
  flags: string[];
  /** Human-readable reason. */
  reason: string;
  /** Whether a block rule fired. */
  blocked: boolean;
  /** Block reason, if any. */
  blockReason: string | null;
}

/** Normalized action — the tool-agnostic representation. */
export interface NormAction {
  /** Action type string, e.g. "payments.charge". */
  actionType: string;
  /** Channel/vendor, e.g. "stripe". */
  channel: string;
  /** Semantic entities as a JSON string. */
  entitiesJson: string;
  /** Norm hash hex (16 chars). */
  normHash: string;
}

/** Decision result from the engine. */
export interface DecisionResult {
  /** The permission decision. */
  permission: Permission;
  /** The normalized action. */
  normAction: NormAction;
  /** Risk score (null if decision was from cache/list). */
  riskScore: RiskScore | null;
  /** How the decision was reached. */
  source: string;
}

/**
 * The permit0 permission engine.
 *
 * Use `Engine.fromPacks()` or `EngineBuilder` to construct.
 */
export class Engine {
  /**
   * Construct an engine from a packs directory.
   *
   * @param packsDir - Path to packs directory (default: "packs")
   * @param profilePath - Optional path to a profile YAML file
   */
  static fromPacks(packsDir?: string, profilePath?: string): Engine;

  /**
   * Evaluate a tool call and return a decision.
   *
   * @param toolName - The tool name (e.g. "bash", "http")
   * @param parameters - Parameters object
   * @param orgDomain - Organization domain (default: "default.org")
   */
  getPermission(
    toolName: string,
    parameters: Record<string, unknown>,
    orgDomain?: string
  ): DecisionResult;

  /**
   * Check the permission for a tool call given as a JSON string.
   *
   * @param jsonStr - JSON string with tool_name, parameters, metadata
   * @param orgDomain - Organization domain (default: "default.org")
   */
  checkJson(jsonStr: string, orgDomain?: string): DecisionResult;
}

/**
 * Builder for constructing a configured Engine.
 */
export class EngineBuilder {
  constructor();

  /** Install a YAML normalizer definition. */
  installNormalizerYaml(yaml: string): void;

  /** Install a YAML risk rule definition. */
  installRiskRuleYaml(yaml: string): void;

  /** Build the engine from the current configuration. */
  build(): Engine;
}
