#![forbid(unsafe_code)]

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

use permit0_types::{Permission, Tier};

/// A human override of an automated decision.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HumanOverride {
    /// The original automated decision.
    pub original_decision: Permission,
    /// What the human decided.
    pub human_decision: Permission,
    /// The norm_hash this override applies to.
    pub norm_hash: permit0_types::NormHash,
    /// Action type string.
    pub action_type: String,
    /// Reason for the override.
    pub reason: String,
    /// ISO 8601 timestamp.
    pub timestamp: String,
    /// Reviewer identity (email, username, etc.).
    pub reviewer: String,
}

/// Features extracted from decision history, suitable for ML training.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrainingFeatures {
    /// Raw risk score (0.0–1.0).
    pub raw_score: f64,
    /// Quantized score (0–100).
    pub score: u32,
    /// Risk tier.
    pub tier: Tier,
    /// Number of flags that fired.
    pub flag_count: usize,
    /// Whether a block rule fired.
    pub blocked: bool,
    /// Per-flag indicators.
    pub flags: HashMap<String, bool>,
    /// Action type string.
    pub action_type: String,
    /// Domain portion of action type.
    pub domain: String,
    /// Verb portion of action type.
    pub verb: String,
    /// What the human decided (the label).
    pub label: Permission,
    /// Whether this was an override of the automated decision.
    pub was_overridden: bool,
}

/// Statistics for a specific action type's decision history.
#[derive(Debug, Clone)]
pub struct ActionStats {
    /// Total number of decisions for this action type.
    pub total_decisions: u64,
    /// Number of times a human approved.
    pub human_approvals: u64,
    /// Number of times a human overrode the automated decision.
    pub overrides: u64,
    /// Override rate (overrides / total_decisions).
    pub override_rate: f64,
    /// Whether this action type is eligible for allowlist promotion.
    pub suggest_allowlist: bool,
    /// Whether this action type is eligible for auto-approve.
    pub suggest_auto_approve: bool,
}

/// Suggestion generated by the learning system.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LearningSuggestion {
    /// Promote to allowlist (>= 50 approvals, < 2% override rate).
    PromoteToAllowlist {
        action_type: String,
        approvals: u64,
        override_rate_pct: u64,
    },
    /// Auto-approve MEDIUM calls (>= 100 approvals, < 5% override).
    EnableAutoApprove {
        action_type: String,
        approvals: u64,
        override_rate_pct: u64,
    },
    /// Pre-route to human (reviewer routes to Human > 80% of the time).
    AddToAlwaysHuman {
        action_type: String,
        human_route_rate_pct: u64,
    },
}
