#![forbid(unsafe_code)]

//! Pack lockfile (`pack.lock.yaml`).
//!
//! A reproducibility manifest committed alongside `pack.yaml` that
//! lists every normalizer, risk rule, alias, and channel-metadata file
//! in the pack with its SHA-256 content hash. Two roles:
//!
//! 1. **Reproducible loading.** When the engine boots with a lockfile
//!    present, it loads only the files listed there — no filesystem
//!    walk, no surprise YAMLs. A community PR can't sneak an
//!    `evil.yaml` into `normalizers/gmail/` without the lockfile diff
//!    showing it.
//!
//! 2. **Phase 2 distribution.** The federated registry will sign over
//!    the lockfile to attest to a pack's contents. Phase 1 ships the
//!    lockfile and the lazy hash check; Phase 2 wires signing on top
//!    of this same artifact.
//!
//! The lockfile is generated by `permit0 pack lock` and committed to
//! the repository. Drift between filesystem and lockfile is a CI
//! failure, not a runtime warning.

use std::path::Path;

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

/// Filename for the pack lockfile. Always at the pack root.
pub const PACK_LOCKFILE_FILENAME: &str = "pack.lock.yaml";

/// Current lockfile schema version. Bump on breaking changes to the
/// schema; engine refuses unknown major versions.
pub const PACK_LOCKFILE_VERSION: u32 = 1;

/// Top-level lockfile structure.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct PackLockfile {
    /// Lockfile schema version (not pack version). Engine refuses
    /// unknown values.
    #[serde(default = "default_lockfile_version")]
    pub lockfile_version: u32,

    /// `<owner>/<name>` — must equal the manifest's `permit0_pack:`.
    pub permit0_pack: String,

    /// Pack version this lockfile was generated against. Bumping
    /// `pack.yaml` version without regenerating the lockfile is a
    /// CI failure.
    pub pack_version: String,

    /// `pack_format` value at generation time. Engine cross-checks
    /// against the live manifest.
    pub pack_format: u32,

    /// ISO 8601 timestamp captured by `permit0 pack lock`.
    /// Informational only; not used in load decisions.
    pub generated_at: String,

    /// Every loadable file in the pack, sorted by path for stable
    /// diffs. Includes normalizer YAMLs, risk rule YAMLs, channel
    /// metadata, alias tables, and the manifest itself.
    pub files: Vec<LockedFile>,
}

fn default_lockfile_version() -> u32 {
    PACK_LOCKFILE_VERSION
}

/// One file pinned by the lockfile.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq, PartialOrd, Ord)]
pub struct LockedFile {
    /// Path relative to the pack directory, forward-slash separated
    /// for cross-platform stability.
    pub path: String,

    /// SHA-256 of the file contents, lowercase hex (64 chars).
    pub sha256: String,

    /// File size in bytes. Cheap drift check that catches truncations
    /// before the hash check runs.
    pub size: u64,
}

/// Errors lockfile operations can surface.
#[derive(Debug, thiserror::Error)]
pub enum LockfileError {
    #[error("io error reading {path}: {source}")]
    Io {
        path: std::path::PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("yaml parse error in {path}: {source}")]
    Parse {
        path: std::path::PathBuf,
        #[source]
        source: serde_yaml::Error,
    },
    #[error("yaml serialize error: {0}")]
    Serialize(#[from] serde_yaml::Error),
    #[error("lockfile version mismatch: file declares {found}, this binary supports {supported}")]
    UnsupportedVersion { found: u32, supported: u32 },
    #[error("lockfile drift: {0}")]
    Drift(String),
}

/// Compute the SHA-256 hex digest of a file's contents.
pub fn sha256_hex(bytes: &[u8]) -> String {
    let mut h = Sha256::new();
    h.update(bytes);
    format!("{:x}", h.finalize())
}

impl PackLockfile {
    /// Read and parse a lockfile. Returns an error if the version is
    /// unsupported (so callers don't have to spread the check).
    pub fn read(path: impl AsRef<Path>) -> Result<Self, LockfileError> {
        let path = path.as_ref();
        let yaml = std::fs::read_to_string(path).map_err(|e| LockfileError::Io {
            path: path.to_path_buf(),
            source: e,
        })?;
        let parsed: PackLockfile =
            serde_yaml::from_str(&yaml).map_err(|e| LockfileError::Parse {
                path: path.to_path_buf(),
                source: e,
            })?;
        if parsed.lockfile_version != PACK_LOCKFILE_VERSION {
            return Err(LockfileError::UnsupportedVersion {
                found: parsed.lockfile_version,
                supported: PACK_LOCKFILE_VERSION,
            });
        }
        Ok(parsed)
    }

    /// Serialize to canonical YAML. Stable key order; lossless round-trip.
    pub fn to_yaml(&self) -> Result<String, LockfileError> {
        Ok(serde_yaml::to_string(self)?)
    }

    /// Find a locked file by relative path. Returns `None` if the path
    /// is not in the lockfile (i.e. a stowaway file that bypassed the
    /// lock step).
    pub fn find(&self, rel_path: &str) -> Option<&LockedFile> {
        self.files.iter().find(|f| f.path == rel_path)
    }

    /// Verify a file's bytes against the lockfile entry. Returns
    /// `Ok(true)` when the hash matches, `Ok(false)` when it diverges,
    /// and `Err` when the file isn't listed in the lockfile at all.
    pub fn verify(&self, rel_path: &str, bytes: &[u8]) -> Result<bool, LockfileError> {
        let entry = self
            .find(rel_path)
            .ok_or_else(|| LockfileError::Drift(format!("{rel_path} not listed in lockfile")))?;
        if entry.size != bytes.len() as u64 {
            return Ok(false);
        }
        Ok(entry.sha256 == sha256_hex(bytes))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_lockfile() -> PackLockfile {
        PackLockfile {
            lockfile_version: PACK_LOCKFILE_VERSION,
            permit0_pack: "permit0/email".into(),
            pack_version: "0.4.0".into(),
            pack_format: 2,
            generated_at: "2026-05-01T00:00:00Z".into(),
            files: vec![
                LockedFile {
                    path: "normalizers/gmail/send.yaml".into(),
                    sha256: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
                        .into(),
                    size: 100,
                },
                LockedFile {
                    path: "risk_rules/send.yaml".into(),
                    sha256: "fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210"
                        .into(),
                    size: 50,
                },
            ],
        }
    }

    #[test]
    fn yaml_round_trip_preserves_contents() {
        let lock = sample_lockfile();
        let yaml = lock.to_yaml().unwrap();
        let parsed: PackLockfile = serde_yaml::from_str(&yaml).unwrap();
        assert_eq!(parsed.permit0_pack, lock.permit0_pack);
        assert_eq!(parsed.pack_version, lock.pack_version);
        assert_eq!(parsed.files.len(), lock.files.len());
    }

    #[test]
    fn find_returns_listed_file() {
        let lock = sample_lockfile();
        assert!(lock.find("normalizers/gmail/send.yaml").is_some());
        assert!(lock.find("normalizers/gmail/missing.yaml").is_none());
    }

    #[test]
    fn verify_matches_correct_bytes() {
        let lock = PackLockfile {
            lockfile_version: PACK_LOCKFILE_VERSION,
            permit0_pack: "permit0/email".into(),
            pack_version: "0.4.0".into(),
            pack_format: 2,
            generated_at: "2026-05-01T00:00:00Z".into(),
            files: vec![LockedFile {
                path: "f.yaml".into(),
                sha256: sha256_hex(b"hello"),
                size: 5,
            }],
        };
        assert!(lock.verify("f.yaml", b"hello").unwrap());
        assert!(!lock.verify("f.yaml", b"world").unwrap()); // wrong content
        assert!(lock.verify("missing.yaml", b"").is_err()); // not in lockfile
    }

    #[test]
    fn unsupported_version_rejected() {
        let yaml = r#"
lockfile_version: 99
permit0_pack: "permit0/email"
pack_version: "0.4.0"
pack_format: 2
generated_at: "2026-05-01T00:00:00Z"
files: []
"#;
        let dir = std::env::temp_dir().join(format!("permit0-lock-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("pack.lock.yaml");
        std::fs::write(&path, yaml).unwrap();
        let err = PackLockfile::read(&path).unwrap_err();
        assert!(matches!(err, LockfileError::UnsupportedVersion { .. }));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn sha256_is_deterministic() {
        assert_eq!(sha256_hex(b"hello"), sha256_hex(b"hello"));
        assert_ne!(sha256_hex(b"hello"), sha256_hex(b"world"));
        // Known SHA-256 of "hello" (no newline).
        assert_eq!(
            sha256_hex(b"hello"),
            "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"
        );
    }
}
