#![forbid(unsafe_code)]

use serde::{Deserialize, Serialize};

/// Status of a bootstrap proposal.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProposalStatus {
    /// Proposed by LLM, awaiting human review.
    Pending,
    /// Approved by human, rules are active.
    Approved,
    /// Rejected by human.
    Rejected,
}

/// A proposed set of rules for a previously unknown action type.
///
/// Generated by the LLM and MUST be approved by a human before activation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BootstrapProposal {
    /// Unique proposal ID.
    pub proposal_id: String,
    /// The action type that triggered bootstrapping.
    pub action_type: String,
    /// The raw tool call that triggered the bootstrap.
    pub raw_tool_call: serde_json::Value,
    /// Proposed normalizer YAML.
    pub normalizer_yaml: String,
    /// Proposed risk rule YAML.
    pub risk_rule_yaml: String,
    /// LLM reasoning for the proposed rules.
    pub reasoning: String,
    /// Current status.
    pub status: ProposalStatus,
    /// ISO 8601 timestamp of creation.
    pub created_at: String,
    /// ISO 8601 timestamp of review (if reviewed).
    pub reviewed_at: Option<String>,
    /// Reviewer identity (if reviewed).
    pub reviewer: Option<String>,
    /// Review notes (if reviewed).
    pub review_notes: Option<String>,
}

/// Result of a bootstrap attempt.
#[derive(Debug)]
pub enum BootstrapResult {
    /// A proposal was generated and is awaiting review.
    ProposalCreated(Box<BootstrapProposal>),
    /// The LLM failed to generate valid rules.
    ProposalFailed(String),
    /// A pending proposal already exists for this action type.
    AlreadyPending(String),
}
